### ISSUE TITLE
Feature Request: Add the format required by game developers for the export function.

### ISSUE THREAD

**Issue by dazui20** [AnimeEffectsDevs/AnimeEffects#10]
As in the title

**Comment by p-yukusai** [comment]
I'm afraid I don't understand what it is that you want, could you please explain it in more detail?

**Comment by dazui20** [comment]
You can select some 2d skeleton animation files required for game development. For example, cocos creator needs to export animations as json and package images into atlas.

**Comment by p-yukusai** [comment]
Oh, Anime Effects is not currently meant for interacting programmatically with the artwork, there is no way to do what you ask without a major rework of core systems and there are far more pressing issues to work on.
It is something I will work on in the future though! For the time being, you can always use the animations done with AnimeEffects in other export formats or you could check out Inochi2D.

**Comment by p-yukusai** [comment]
This issue will be reopened when and if an SDK is being developed.
