### ISSUE TITLE
Add a Mask Creating Tool to the toolbox

### ISSUE THREAD

**Issue by genestrashcan** [AnimeEffectsDevs/AnimeEffects#11]
Add a Mask Creating Tool to the toolbox

It should be similar to the mask tool in adobe after effects. It should have features like mask path, curvature adjustment, invert mask, and feathering of edges.

I want to create an animation and I need to mask part of a layer it is in so the points in the mask move around to make the part of the layer show where I need it to.

I have put an image in here so you know what feature I am talking about.

![maxresdefault](https://user-images.githubusercontent.com/11165643/212521274-c5a10711-721c-4c65-a5a4-1f75234a5b55.jpg)

**Comment by p-yukusai** [comment]
That's a tall order now isn't it? 😆 
I'll research this further though, it does seem as an important feature to have.
You can for the time being use the mesh creating tool available to "mask", though it's essentially cropping, all parts of the layer that have not been meshed.

**Comment by p-yukusai** [comment]
Won't fix for now, we'll do this later in a future version of AnimeEffects
