### ISSUE TITLE
add support for tiff image format for layered images.

### ISSUE THREAD

**Issue by genestrashcan** [AnimeEffectsDevs/AnimeEffects#15]
add support for tiff image format for layered images.

I would like to use a format with better compression than PSD that supports multiple layers.

**Comment by p-yukusai** [comment]
Added support for tiff images, there is no support for layering however, as Qt will load the image into a single file and not allow me to access the layer information, I might make a tiff loader using a library to access the information, but that'll take awhile.

**Comment by p-yukusai** [comment]
Layered tiff support won't be added for the foreseeable future I'm afraid, I'll keep it in mind for later however 😄
