### ISSUE TITLE
make ability to import individual images as layers easier

### ISSUE THREAD

**Issue by genestrashcan** [AnimeEffectsDevs/AnimeEffects#16]
The ability to import individual images as layers is hard to do unless you know EXACTLY what you're doing. You must import each image under a well-hidden menu under resources and then map each to its own layer.

make it easier to set up and get individual layers created as layer objects.

**Comment by p-yukusai** [comment]
We've streamlined it a bit by removing the menu and just having a "Add resources" button, this code is not on this repository just yet.
Other than that, what do you think would make this process easier? 🤔
