### ISSUE TITLE
add ability to change hue / saturation of a layer by keyframe

### ISSUE THREAD

**Issue by genestrashcan** [AnimeEffectsDevs/AnimeEffects#18]
add the ability to change hue/saturation of a layer by keyframe.

I am creating a video where a Naga girl (think medusa) gives a girl a "Snake Massage" and I want to adjust hue/saturation by keyframe to have the girl's face turn slightly red during each "coil squeeze"

![4 - Copy](https://user-images.githubusercontent.com/11165643/215389898-6477587f-3e3a-4dc3-be03-85dada9b24ac.jpg)

**Comment by p-yukusai** [comment]
Added HSV keys for layer nodes, pending merge.
