### ISSUE TITLE
Get the latest version of anime effects up on the official website

### ISSUE THREAD

**Issue by genestrashcan** [AnimeEffectsDevs/AnimeEffects#22]
Get the latest version of anime effects up on the download page of the official anime effects website

http://animeeffects.org/en/?page_id=6

**Comment by p-yukusai** [comment]
We do not own the http://animeeffects.org page, nor do we have any access to it, as we have been unable to contact hidefuku (the original developer).
The website for this fork is https://animeeffectsdevs.github.io/
