### ISSUE TITLE
Add a way to set easing on keyframes in bulk

### ISSUE THREAD

**Issue by genestrashcan** [AnimeEffectsDevs/AnimeEffects#23]
Currently setting the easing settings on keyframes takes a very long time because you have to set the easing settings of each set of keyframes per layer one at a time.

Add a way to set the easing settings on keyframes in bulk.

**Comment by p-yukusai** [comment]
We are planning on allowing bulk setup of most (if not all) keys👍

**Comment by genestrashcan** [comment]
when is 1.6 coming out

**Comment by p-yukusai** [comment]
Probably sometime in November if time allows for it.

**Comment by p-yukusai** [comment]
Added to latest indev, thank you for your feedback.
