### ISSUE TITLE
git throws Illegal byte sequence when cloning repository

### ISSUE THREAD

**Issue by Aodaruma** [AnimeEffectsDevs/AnimeEffects#26]
**Describe the bug**
When cloning a repository with Git or Github Desktop, an error message "Illegal byte sequence" occurs. This is likely because the file name ".github/ISSUE_TEMPLATE/bug-report-..." contains a character encoding that is not compatible with UTF8.

**To Reproduce**
1. `git clone https://github.com/AnimeEffectsDevs/AnimeEffects.git`

**Expected behavior**
The repository should be cloned without any errors.

**Screenshots**
Instead of a screenshot, I'll provide an error message:
```
Cloning into '/Users/aodaruma/Documents/GitHub/AnimeEffects'...
remote: Enumerating objects: 5157, done.        
remote: Counting objects: 100% (1192/1192), done.        
remote: Compressing objects: 100% (672/672), done.        
remote: Total 5157 (delta 601), reused 1043 (delta 487), pack-reused 3965        
Receiving objects: 100% (5157/5157), 4.54 MiB | 23.04 MiB/s, done.
Resolving deltas: 100% (3570/3570), done.
error: unable to create file .github/ISSUE_TEMPLATE/bug-report-🪲.md: Illegal byte sequence
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

Would you like to retry cloning ?
```

**Operating System:**
```zsh
% sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2026
```

**Additional context**
I found an article seems to be helpful at:
https://stackoverflow.com/questions/57732278/git-checkout-failed-with-illegal-byte-sequence

**Comment by p-yukusai** [comment]
I see, this is a problem specific to posix systems it seems, as I cannot replicate it myself.

<details>
<summary>pwsh output</summary>

``` powershell
Cloning into 'AnimeEffects'...
remote: Enumerating objects: 5165, done.
remote: Counting objects: 100% (1199/1199), done.
remote: Compressing objects: 100% (679/679), done.
remote: Total 5165 (delta 603), reused 1042 (delta 487), pack-reused 3966
Receiving objects: 100% (5165/5165), 4.56 MiB | 7.95 MiB/s, done.
Resolving deltas: 100% (3572/3572), done.
```

</details>

I believe that the illegal byte in this case might just be the 🪲 emoji I added to the filename, so I've renamed both issue template files to better conform to UTF-8 encoding.
Thanks for the detailed report and please let me know if this fixed the issue. 🙇

**Comment by p-yukusai** [comment]
Closing this due to lack of info, if the bug wasn't fixed feel free to open the issue anew.
