### ISSUE TITLE
which ffmpeg

### ISSUE THREAD

**Issue by puppiescouts** [AnimeEffectsDevs/AnimeEffects#28]
im having a hard time trying to find the right ffmpeg to use for animeeffects..
i initially tried downloading the ffmpeg off the website but when i clicked the link it gave me an error that it was blocked
i was wondering if the ffmpeg got changed or deleted? or if someone could point me in the right direction
thank you

**Comment by p-yukusai** [comment]
Sorry for the delay.
If you use our latest version, you can just go to the options menu -> general settings -> ffmpeg and click on "Download and automatically setup"

**Comment by p-yukusai** [comment]
I'll close this issue assuming it worked out for you, if you've got any other issues please let me know
