### ISSUE TITLE
add suport for sound

### ISSUE THREAD

**Issue by kontlo7171** [AnimeEffectsDevs/AnimeEffects#30]
Adding support for sound can make it easier to create animations, especially for narration, lipsync, and storytelling. I don't think it needs to be too advanced, just adding one sound to keyframe tab would be great, as it was in the old version of Krita Animation. But if it can add sound with layers, I think it will greatly enhance the capabilities of this software.

**Comment by p-yukusai** [comment]
It's already on our todo list!
We'll keep you posted on our progress.

**Comment by genestrashcan** [comment]
when is 1.6 coming out?

**Comment by p-yukusai** [comment]
Soon™

**Comment by p-yukusai** [comment]
Will start work on sound support ;)

**Comment by p-yukusai** [comment]
Sound system integrated 
https://github.com/AnimeEffectsDevs/AnimeEffects/pull/67

Thanks for your support.
