### ISSUE TITLE
Failed to Rename Project File Bug

### ISSUE THREAD

**Issue by genestrashcan** [AnimeEffectsDevs/AnimeEffects#42]
**Describe the bug**

Trying to save a project in windows 10 and then rename the file even when giving the program administrative privileges causes a "failed to rename file" error to pop up.

**To Reproduce**

1. Create a new project and save it.
2. rename the project file.
3. open the project and try to save it.
4. This pops up

![image](https://github.com/AnimeEffectsDevs/AnimeEffects/assets/11165643/9adead2c-f10b-4dde-bca5-d786e3dad6fa)

**Expected behavior**

The program should save the file normally.

**Screenshots**

![image](https://github.com/AnimeEffectsDevs/AnimeEffects/assets/11165643/13ca2f2f-4cb4-4b29-a444-a137ff2bc8d3)
![photo (2) - Copy](https://github.com/AnimeEffectsDevs/AnimeEffects/assets/11165643/705b5512-99a2-4485-b8ca-8478f9bd9d0a)

**Operating System:**

Windows 10. 

**Software version**

Please tell us the version of AnimeEffects with the bug:

1.5.2 with anime effects given admin privileges

**Additional context**

**NEW FIND: Restarting Windows and opening the project file and saving will cause the bug.**

**Renaming the project file will trigger the bug when trying to save.**

**Somehow i am able to save the file as a new project in anime effects and the bug won't happen until one of the two above happens.**

**Comment by p-yukusai** [comment]
I was unable to replicate the bug, what are you renaming your project to?

**Comment by p-yukusai** [comment]
Closed as stale, please comment to open the issue again with more information.
