### ISSUE TITLE
Linux main menu and uninstallation option

### ISSUE THREAD

**Issue by Mint-me123** [AnimeEffectsDevs/AnimeEffects#44]
Hi
It looks like an amazing software however I have not been able to even get beyond opening the sample project. If I want to uninstall it (Linux Mint 21.3) how do I do that?
Also I think it would be a good idea to add a menu item after installation. Using ./AnimeEffects  works fine and can be put in a launcher but still.

**Comment by p-yukusai** [comment]
Hello!
I recommend you check out [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher), that'll let you have all the features you're asking for, as the AppImage is a stand-alone executable and by itself it cannot allow you to do any of the things you've mentioned.
Also if you currently want to uninstall AnimeEffects you need simply to delete the file.

**Comment by Mint-me123** [comment]
Hello. Thank you. Oh. I thought it was "installed" because it was a github pull and there was no appimage or icon to be found. I can try the appimage launcher you suggest but the easier thing is to make a desktop launcher calling a bash script which cd to the folder of animeeffect src and then calls the program with ./AnimeEffects  as per your instructions. You will then also get the option of putting the launcher in the main launch menu.

**Comment by p-yukusai** [comment]
I'll consider adding that later on :D
