### ISSUE TITLE
Copying keyframes issue

### ISSUE THREAD

**Issue by BCcat069** [AnimeEffectsDevs/AnimeEffects#46]
I don't know is it just my computer or not. The program crash after trying to copy FFD keyframes that have new image assign on the same keyframe

![image](https://github.com/AnimeEffectsDevs/AnimeEffects/assets/164674840/a428719b-0011-4ae1-9225-ce69a6e80519)

My operating system is Windows 10
AnimeEffects version 1.5.2

Anyway! I really appreciate you for providing this wonderful program and thank you for listening my issue :D

**Comment by FleiraSekai** [comment]
Same problem here, and I've also noticed that FFD doesn't apply on new images. That's pretty annoying, especially crashing while I just try to copy the frame Q_Q

Thanks for this wonderful program, but it would be awesome if you can fix these!

**Comment by p-yukusai** [comment]
Known issue, I commented on it on the release notes for the version where I added the feature.
I forgot to make it not crash, though, so I'll check that out later.

**Comment by p-yukusai** [comment]
Fixed, thanks for the report!
