### ISSUE TITLE
(will be solved in future update) "Segmentation fault (core dumped)" when exporting animation normally in Ubuntu Linux xfce desktop

### ISSUE THREAD

**Issue by PhoenixStormJr** [AnimeEffectsDevs/AnimeEffects#49]
(However, legacy export works fine.) (temporary solution: add .mp4, .png, or whatever the ending of the file is)
**I tried to export a basic animation, single image, and got "Segmentation fault (core dumped)" error.**

**To Reproduce**
1. Open AnimeEffects.appimage (or whatever the name is) on Linux Ubuntu
2. Click on "file" and "new project" initial resource can be whatever. I did a PNG of Yoshi.
3. click "file" and "export project" (not legacy) and "Export", name it, and click "save"
![ScreenshotAnimeEffectsExportFail](https://github.com/AnimeEffectsDevs/AnimeEffects/assets/66498788/4cfd24c6-e397-4c9d-890e-e9e3ab2bebb3)

**Expected behavior**
I honestly don't know? Anything but a crash...

**Operating System:**
Please tell us your OS version. Ex. Windows 11, Ubuntu 22.04, macOS Big Sur 11.6, etc.

phoenix@phoenix:~/Downloads/AnimeEffects-Linux$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Software version**
Please tell us the version of AnimeEffects with the bug, the way to get it is to:
1. This website: https://github.com/AnimeEffectsDevs/AnimeEffects/releases/tag/v1.5.2

**Comment by p-yukusai** [comment]
Known issue, already resolved but not released.
Please input the suffix with the file name when you export to solve it for now, thanks for the report.
![image](https://github.com/AnimeEffectsDevs/AnimeEffects/assets/85849071/0a5d6e4b-45f0-4975-9f57-0459ae10b541)

**Comment by PhoenixStormJr** [comment]
Thanks for the quick reply. I'm sorry I didn't check for any documentation. I hope I didn't come across as annoying or something. Sorry if I did, I'm not that experienced with this type of stuff.

> Known issue, already resolved but not released. Please input the suffix with the file name when you export to solve it for now, thanks for the report. ![image](https://private-user-images.githubusercontent.com/85849071/331837553-0a5d6e4b-45f0-4975-9f57-0459ae10b541.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNzY4NjAsIm5iZiI6MTcxNjA3NjU2MCwicGF0aCI6Ii84NTg0OTA3MS8zMzE4Mzc1NTMtMGE1ZDZlNGItNDVmMC00OTc1LTlmNTctMDQ1OWFlMTBiNTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDIzNTYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwYTIzMjYxOTYxMDMyZTVmOTk4NTA4ZjQzNDhiNzI0YjVhZTBlNTMwOWEyYWYzMzQwMGY5ZTZhMzcwZWFlMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9i4BwpEQzAlRK4IK3-qn4q2SaL8UVlaGX-Yd1UOUHqg)

**Comment by p-yukusai** [comment]
> Thanks for the quick reply. I'm sorry I didn't check for any documentation. I hope I didn't come across as annoying or something. Sorry if I did, I'm not that experienced with this type of stuff.

It's alright don't worry, I appreciate bug reports so keep at it, it won't always be a known issue ;)
