### ISSUE TITLE
Add support for jpeg xl images

### ISSUE THREAD

**Issue by genestrashcan** [AnimeEffectsDevs/AnimeEffects#52]
add support for jpeg xl (jxl) images as layers if it hasn't been done yet.

jpeg xl has a even higher compression ratio than webp in transparent images.

**Comment by p-yukusai** [comment]
We're not planning on supporting new formats that aren't already supported by Qt's ImageFormats plugin, I'm planning on supporting it later on for another project I'm planning but for now won't fix.
