### ISSUE TITLE
i'm trying to export but it's not exporting

### ISSUE THREAD

**Issue by helynnekiwaii** [AnimeEffectsDevs/AnimeEffects#55]
i'm trying to find /tools file in AnimeEffects file and I can't find ittt

**Comment by helynnekiwaii** [comment]
ok nvm i immediately solved it just put it in animeeffects u dont need to find /tools

**Comment by p-yukusai** [comment]
You can also just create the /tools folder and it'll work the same

**Comment by helynnekiwaii** [comment]
okay reopening im trying to export as gif but nothing gets exported. the width is 500 and the height is 800

**Comment by helynnekiwaii** [comment]
ok so apparently i can't export gif but i can export mp4 and mov whaat

**Comment by p-yukusai** [comment]
What version and which exporter are you using?

**Comment by helynnekiwaii** [comment]
1.5.2 and legacy
oh that might be why, im gonna download 1.4.2 instead

**Comment by p-yukusai** [comment]
Don't use the legacy exporter, instead use the new one as it has various improvements.
Do not downgrade either as there are various bugfixes in the newer version, do be mindful that there are some known bugs that I'm yet to release a fix for, even though it's already been made:
- Export fails if it has spaces on the path, please use names without spaces in folders that also don't have spaces in them for now.
- Write error on legacy exporter on flatpak, export with the new exporter.
- Crash on export if the suffix hasn't been typed when deciding export location, if this happens to you please type your suffix (.gif, .mp4) at the end of the name of your export.

**Comment by helynnekiwaii** [comment]
ahh tysm! it works now, and the detail errors do a great job on telling ppl what's wrong in order for it to be exported. however i have a problem; when i exported a gif and checked the anim out, the movement started smearing, like a smearing effect. i did not have a bg at a time, was that the problem?

**Comment by p-yukusai** [comment]
Yup, we support transparency now and as such if you don't enable transparency on the options and don't have a background you'll encounter smearing.
I recommend you add one or enable transparency

**Comment by helynnekiwaii** [comment]
oop i just got an error message that said to send it to the devs, so I'm putting it here for the mean time

FFmpeg Object
-----
Argument: -y -hwaccel auto -f image2pipe -framerate 24 -i - -b:v 0 -r 24 -f gif -threads 0 -lavfi split[v],palettegen,[v]paletteuse=alpha_threshold=128 -gifflags -offsetting -loop 1 C:/Users/helyn/Dropbox/PC/Documents/drawing stuff 5/OCS!!/oc 2024/draw ur ocs as this/animeeffects gifs/milan_weeping_lol.gif.
Executable: .\tools\ffmpeg.
Result: 1.
Log: -Ready read-
ffmpeg version 4.1.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20190212
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100

Input #0, image2pipe, from 'pipe:':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: png, rgba(pc), 540x852 [SAR 3780:3780 DAR 45:71], 24 fps, 24 tbr, 24 tbn, 24 tbc

[NULL @ 000001f0403d5180] Unable to find a suitable output format for 'stuff'
stuff: Invalid argument
.
Error log: -Ready read-
FFmpeg error detected, stopping render..
------
Export Results
-----
Result: 4.
Export String: .

**Comment by helynnekiwaii** [comment]
> Yup, we support transparency now and as such if you don't enable transparency on the options and don't have a background you'll encounter smearing. I recommend you add one or enable transparency

ah ty i have a bg ready, ill close this thread once i believe i have no more problems

**Comment by p-yukusai** [comment]
You have spaces on your folder, as stated before that's a known bug for now

**Comment by helynnekiwaii** [comment]
OH I HAD SPACE on the folder

**Comment by p-yukusai** [comment]
If you have any other issues you can open a new issue or ask us about it on our discord ❤️
