### ISSUE TITLE
what do i do to fix? i cant export my work a

### ISSUE THREAD

**Issue by burgertownforever** [AnimeEffectsDevs/AnimeEffects#56]
FFmpeg Object
-----
Argument: -y -hwaccel auto -f image2pipe -framerate 24 -i - -b:v 0 -r 24 -pix_fmt yuv420p -f mp4 -threads 0 C:/Users/roan pena/OneDrive/Desktop/finished products animated/pro1.mp4.
Executable: .\tools\ffmpeg.
Result: 1.
Log: -Ready read-
ffmpeg version 2024-07-10-git-1a86a7a48d-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libopenjpeg --enable-libquirc --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-libqrencode --enable-librav1e --enable-libsvtav1 --enable-libvvenc --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      59. 28.100 / 59. 28.100
  libavcodec     61. 10.100 / 61. 10.100
  libavformat    61.  5.101 / 61.  5.101
  libavdevice    61.  2.100 / 61.  2.100
  libavfilter    10.  2.102 / 10.  2.102
  libswscale      8.  2.100 /  8.  2.100
  libswresample   5.  2.100 /  5.  2.100
  libpostproc    58.  2.100 / 58.  2.100

Input #0, image2pipe, from 'fd:':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: png, rgba(pc, gbr/unknown/unknown), 2000x2000 [SAR 3780:3780 DAR 1:1], 24 fps, 24 tbr, 24 tbn
[AVFormatContext @ 000002193083a200] Unable to choose an output format for 'pena/OneDrive/Desktop/finished'; use a standard extension for the filename or specify the format manually.
[out#1 @ 000002193083a100] Error initializing the muxer for pena/OneDrive/Desktop/finished: Invalid argument
Error opening output file pena/OneDrive/Desktop/finished.
Error opening output files: Invalid argument
.
Error log: -Ready read-
FFmpeg error detected, stopping render..
------
Export Results
-----
Result: 4.
Export String: .

**Comment by p-yukusai** [comment]
Known issue, please export to a folder without spaces with a file name that also does not have spaces.
This has been fixed but is pending a release

**Comment by burgertownforever** [comment]
thanks
