### ISSUE TITLE
Program problem

### ISSUE THREAD

**Issue by 6Ieed** [AnimeEffectsDevs/AnimeEffects#57]
So i'm not sure whats happening or why this happens but i've constantly redownloaded the program because it won't let me export my animations or it says the animations are corrupt. Now that im tryna to redownload ffmpeg it also says this and that i must speak to a dev. 

Whenever i run the program it also says that windows is protecting my pc from the program. May i get help?

![bug i think](https://github.com/user-attachments/assets/31f8978e-c9ff-4438-b277-213d6fe53969)
![bug too i think (1)](https://github.com/user-attachments/assets/33caf778-7a16-4e9b-9f1d-57c9390226f7)

**Comment by p-yukusai** [comment]
Regarding defender please ignore it or add the executable to your exclusions, this is just because we don't do digital signatures because they are too expensive. 
From my experience that error means you dont have curl or wget so youll have to download FFmpeg manually, could you please tell me what version of windows are you running?

**Comment by 6Ieed** [comment]
Hello! I understand. I am running windows 11 I am SO sorry for the late reply.

**Comment by p-yukusai** [comment]
No worries, just follow these steps:

- Press your Windows key
- Type "powershell" and press enter
- Type into the console the command `winget install FFmpeg` and press enter
- Follow the instructions on screen
- Profit

**Comment by 6Ieed** [comment]
im confused i dont think its showing any instructions it shows this 
![image](https://github.com/user-attachments/assets/5848a24c-ec1b-46c5-b9e1-d79fea53f135)

**Comment by p-yukusai** [comment]
You're done, try to export now!

**Comment by 6Ieed** [comment]
I did and its still not working it still says my animations are corrupt

**Comment by 6Ieed** [comment]
and when i click "download and automatically setup ffmpeg" it also still says and error occured, idk if im doing this right atp

**Comment by p-yukusai** [comment]
Weird, I'll upload a version with FFmpeg already on it for you to try, this is still in development but should have some bug fixes.
https://litter.catbox.moe/wv9y4p.zip

**Comment by 6Ieed** [comment]
I tried testing exporting and this is what i got

![image](https://github.com/user-attachments/assets/4a2c3734-12c9-4429-907c-803689d9d56a)

**Comment by p-yukusai** [comment]
Change the canvas size on your project menu to an even number for both dimensions and deselect the transparency option if you're not using it

**Comment by 6Ieed** [comment]
ah okay ill try again

**Comment by 6Ieed** [comment]
![image](https://github.com/user-attachments/assets/b0d11803-07a4-4144-952d-298f2f362119)


hey just incase do umean like this?

**Comment by p-yukusai** [comment]
> ![image](https://private-user-images.githubusercontent.com/108552448/352011220-b0d11803-07a4-4144-952d-298f2f362119.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MjY1MzIsIm5iZiI6MTcyMTkyNjIzMiwicGF0aCI6Ii8xMDg1NTI0NDgvMzUyMDExMjIwLWIwZDExODAzLTA3YTQtNDE0NC05NTJkLTI5OGYyZjM2MjExOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxNjUwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMmM1OWFkNzkxZTE3ZmE0ZjFmMWU2ZTcxY2ZjNjlhYTQzZWJmMGY5ODU2N2VlY2VkZWMyYjYwYmJlN2E1NWZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pcZVzjyZ074ojYhrenB-bHyqhnVyFLEEcL6yW-M0D3o)
> 
> hey just incase do umean like this?

You need to set your canvas height and width to odd numbers, you can set the aspect ratio to custom and change it to 736 by 294, I also recommend you lower your FPS to 30 and your intermediate to PPM, the GIF format doesn't like framerates past 30 and PPM is a faster format to work with if you're not using transparency, if you are you will need PNG though

**Comment by 6Ieed** [comment]
Oh how do i export it as a video instead? thats what im tryna do because the concept im tryna export has a background already so no worries about transparency

**Comment by 6Ieed** [comment]
Hey you still there? I wanna export my animation as a video instead :) and im struggling to understand what you meant in ur previous response. I just wanna fix the "corruption" issue on my end everytime i export.

**Comment by p-yukusai** [comment]
Oh sorry didn't see the comments, you can just select your suffix on export with the drop down menu, my previous response was related to the settings in the exporter that you should use, I strongly recommend you take further inquiries to the Discord for AnimeEffects to be more expedient but if you can't that's okay too.

**Comment by 6Ieed** [comment]
Ah okay, i don't have discord unfortunately due to being banned reasoning because my acc was underage. I didn't rlly understand how to make an acc at the time lol, but i followed exactly what you said in your previous in this is what i got.

(for legacy)
![image](https://github.com/user-attachments/assets/48236313-642c-49bc-991b-761befef937f)

as for the new version
![image](https://github.com/user-attachments/assets/42e31d29-e926-45b2-9ded-d7e58b2b8e0f)

Would you strongly recommend i go to the discord for the issue then?

**Comment by p-yukusai** [comment]
I do mostly because it's a lot faster for me, aslo please send me the error details not just the messagebox, for that just click on "Show Details" and grab all the text there

**Comment by 6Ieed** [comment]
Ah wait I think i solved and figured the issue out, thank you! :) Can you also give me the discord link just incase for further issues if i have any in the future, my animation finally exported properly and is no longer corrupt!

**Comment by p-yukusai** [comment]
https://discord.com/invite/sKp8Srm
