### ISSUE TITLE
Hello! When Im going to export the animation, the program presents an error~

### ISSUE THREAD

**Issue by KiraVoid-1** [AnimeEffectsDevs/AnimeEffects#58]
I just finished my first animation and when I was going to export it, it shows me this warning:
"The export process stopped abnormaly, please send this info to the devs"

FFmpeg Object
-----
Argument: -y -hwaccel auto -f image2pipe -framerate 24 -i - -b:v 0 -r 24 -pix_fmt yuv420p -f mp4 -threads 0 C:/Users/thiag/OneDrive/Área de Trabalho/AnimeEffects/aaa.mp4.
Executable: .\tools\ffmpeg.
Result: 1.
Log: -Ready Write-
ffmpeg version 5.1.2-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100

Input #0, image2pipe, from 'pipe:':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: png, rgba(pc), 2000x2000 [SAR 4724:4724 DAR 1:1], 24 fps, 24 tbr, 24 tbn

[NULL @ 0000022eee125740] Unable to find a suitable output format for 'de'
de: Invalid argument
.
Error log: -Ready read-
FFmpeg error detected, stopping render..
------
Export Results
-----
Result: 4.
Export String: .

Could you help me with that please? I'll be waiting for it ^^

Thank you for your attention!!

**Comment by p-yukusai** [comment]
Known issue, please don't use spaces on the path you're exporting.
This has already been fix but the release is pending other stuff getting done

**Comment by KiraVoid-1** [comment]
Hey!

I didn't get it, what do you mean with "don't use spaces on the path",
like, what spaces?
I appreciate your help!!

Em ter., 30 de jul. de 2024 às 13:51, Yukusai ***@***.***>
escreveu:

**Comment by p-yukusai** [comment]
"C:/Users/thiag/OneDrive/Área de Trabalho/AnimeEffects/aaa.mp4"
So your folder "Área<space>de<space>Trabalho" has spaces in it, please use a folder that doesn't have any and a file name that equaly does not use spaces, so all the letters are together, this is because I forgot to add suport for these until after the release of the latest version, this issue is fixed in the code but a new version with the fix is pending.
