### ISSUE TITLE
TODO : Add Cmake support

### ISSUE THREAD

**Issue by SeleDreams** [AnimeEffectsDevs/AnimeEffects#6]
- Adding CMake support
- Managing dependencies for an easy build and easy build error solving (making it obvious which dependencies are lacking)

I can be assigned to this task

**Comment by SeleDreams** [comment]
started work on PR https://github.com/AnimeEffectsDevs/AnimeEffects/pull/7

**Comment by p-yukusai** [comment]
Merge request for CMake support was made by @GbotHQ, closing this issue.
