### ISSUE TITLE
FFmpeg ; An error has occurred, please send the bellow info to the developers.

### ISSUE THREAD

**Issue by jirajpg** [AnimeEffectsDevs/AnimeEffects#60]
Filename : ffmpeg-macos
Is Executable : False
Download params : Hardcoded API | gitFile: ffmpeg-macos | ID: 97679141
Download path : /Users/mjira/Desktop/AnimeEffects.app/tools

**Comment by p-yukusai** [comment]
Known issue, I forgot to make FFmpeg executable on POSSIX systems, you can manually download FFmpeg using brew.
