### ISSUE TITLE
I pressed to download and automatically set up the FFmpeg but it says error and to send smth to the developer,

### ISSUE THREAD

**Issue by water08gacha** [AnimeEffectsDevs/AnimeEffects#70]
<img width="424" alt="Screen Shot 2024-12-13 at 9 19 06 PM" src="https://github.com/user-attachments/assets/faddc1e6-1399-4dfc-9179-7d22b0981ee9" />

The details written below is

Filename : 
Is Executable : False
Download params : Hardcoded API | gitFile: ffmpeg-macos | ID: 97679141
Download path : /private/var/folders/9v/91bt_bg140x7q0c26fjc4rc00000gn/T/AppTranslocation/08AFFFFF-7CB4-4EA6-8468-24BC95BF1C02/d/AnimeEffects.app/tools

Does anyone know how to fix this issue or how to contact the developer?

**Comment by p-yukusai** [comment]
Known issue where i forgot to make ffmpeg executable on unix systems, its fixed pending release v1.6
For now install ffmpeg using brew
